server:
  port: 8081
spring:
  application:
    name: aloha
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: orderservice
          uri: lb://feign-nacos-service-order
          predicates:
            - Path=/order-serv/feign/consumer/**
          filters:
            - StripPrefix=1
